### ISSUE TITLE
SyntaxError: Unexpected token

### ISSUE THREAD

**Issue by dinosaw** [hocza/twitch-username-checker#1]
The script / app seems to crash sometimes with the following error. I thought it might be due to invalid characters in my dict.txt, but it seems to be random. Any ideas?

```
SyntaxError: Unexpected token <
    at Object.parse (native)
    at Request._callback (/twitch-username-checker/twitch.js:19:20)
    at Request.self.callback (/twitch-username-checker/node_modules/request/request.js:354:22)
    at Request.EventEmitter.emit (events.js:98:17)
    at Request.<anonymous> (/twitch-username-checker/node_modules/request/request.js:1207:14)
    at Request.EventEmitter.emit (events.js:117:20)
    at IncomingMessage.<anonymous> (/twitch-username-checker/node_modules/request/request.js:1153:12)
    at IncomingMessage.EventEmitter.emit (events.js:117:20)
    at _stream_readable.js:920:16
    at process._tickCallback (node.js:415:13)
```

**Comment by hocza** [comment]
oh wow for some reason I did not notice this Issue.

Is it still bother you?
Can you give me your dict.txt?

**Comment by dinosaw** [comment]
No worries. It's been a while since I used the script. I'll try and reproduce the error and report back with the dict.txt

**Comment by dinosaw** [comment]
Geez now look who didn't respond, hah! Sorry buddy. I just reproduced this error using the following dictionary:

http://pastebin.com/raw.php?i=WrbDaWdp

It got up to the user 'jamel' (Line 675)
